import AppKit
// The virtual main volume selector lives in AudioToolbox's AudioHardwareService, not CoreAudio.
import AudioToolbox
import CoreAudio
import Foundation
import IOKit.ps
import MacLinkKit

/// Reads and drives the bits of the Mac that are not raw input events: volume, battery, clipboard,
/// and the handful of shell-level actions like locking the screen.
@MainActor
final class SystemController {

    private let input: InputSynthesizer

    /// Used only for the commands the symbolic-hotkey machinery owns. See `SystemEventsBridge`.
    let events = SystemEventsBridge()

    init(input: InputSynthesizer) {
        self.input = input
    }

    // MARK: - Media

    func handle(_ command: MediaCommand) {
        switch command {
        case .playPause: input.postMediaKey(.play)
        case .nextTrack: input.postMediaKey(.next)
        case .previousTrack: input.postMediaKey(.previous)
        case .volumeUp: input.postMediaKey(.soundUp)
        case .volumeDown: input.postMediaKey(.soundDown)
        case .mute: input.postMediaKey(.mute)
        case .brightnessUp: input.postMediaKey(.brightnessUp)
        case .brightnessDown: input.postMediaKey(.brightnessDown)
        case .keyboardBrightnessUp: input.postMediaKey(.illuminationUp)
        case .keyboardBrightnessDown: input.postMediaKey(.illuminationDown)
        }
    }

    // MARK: - System commands

    func handle(_ command: SystemCommand) {
        switch command {
        // Mission Control, Spaces, App Exposé, Launchpad, screenshots and screen lock are all
        // symbolic hotkeys. macOS 26 will not fire those from a synthetic event, so they go through
        // System Events instead — see `SystemEventsBridge` for the measurements behind that.
        case .missionControl: systemShortcut(.special(.up), [.control])
        case .applicationWindows: systemShortcut(.special(.down), [.control])
        case .spaceLeft: systemShortcut(.special(.left), [.control])
        case .spaceRight: systemShortcut(.special(.right), [.control])
        case .showDesktop: systemShortcut(.special(.f11), [])
        // Launchpad no longer exists as of macOS 26; F4 is what its key sent, and now reaches the
        // Applications view that replaced it.
        case .launchpad: systemShortcut(.special(.f4), [])
        case .screenshotFull: systemShortcut(.character("3"), [.command, .shift])
        case .screenshotRegion: systemShortcut(.character("4"), [.command, .shift])
        case .lockScreen: systemShortcut(.character("q"), [.command, .control])
        // The app switcher needs the modifier genuinely held, which a posted event does not manage.
        case .switchAppForward: systemShortcut(.special(.tab), [.command])
        case .switchAppBackward: systemShortcut(.special(.tab), [.command, .shift])

        // Ordinary key equivalents. Any app handles these, so they stay on the cheaper path.
        case .quitApp: input.press(.character("q"), modifiers: [.command])
        case .closeWindow: input.press(.character("w"), modifiers: [.command])

        case .sleepDisplay: runTool("/usr/bin/pmset", ["displaysleepnow"])
        case .sleepSystem: runTool("/usr/bin/osascript", ["-e", "tell application \"System Events\" to sleep"])
        }
    }

    private func systemShortcut(_ key: KeyCode, _ modifiers: [SystemEventsBridge.Modifier]) {
        guard let code = virtualKeyCode(for: key) else { return }
        events.send(keyCode: code, modifiers: modifiers)
    }

    private func virtualKeyCode(for key: KeyCode) -> Int? {
        switch key {
        case .special(let special): return Int(VirtualKeys.code(for: special))
        case .character(let character): return VirtualKeys.code(forCharacter: character).map(Int.init)
        }
    }

    @discardableResult
    private func runTool(_ path: String, _ arguments: [String]) -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: path)
        process.arguments = arguments
        do {
            try process.run()
            return true
        } catch {
            NSLog("MacLink: failed to run %@: %@", path, error.localizedDescription)
            return false
        }
    }

    // MARK: - Clipboard

    /// Types that say "do not treat this as ordinary clipboard content".
    ///
    /// The `org.nspasteboard.*` set is the convention clipboard managers agree on (nspasteboard.org);
    /// `com.apple.is-remote-clipboard` is what macOS puts on content that arrived from another device
    /// over Universal Clipboard.
    private enum PasteboardMarker {
        static let remote = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")
        static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    }

    /// Reads the Mac's clipboard as text, or nil if we should keep our hands off it.
    ///
    /// `automatic` is true for the background sync and false when the user explicitly asked. The
    /// distinction matters because the background path must be a good citizen of the Mac's own
    /// ecosystem, and there are two ways to fail at that:
    ///
    /// - **Universal Clipboard content is a lazy promise.** When your iPhone copies something, the
    ///   Mac's pasteboard holds a placeholder and fetches the payload only when something actually
    ///   reads it. Calling `string(forType:)` on a one-second poll forces that fetch every single
    ///   time, defeating the laziness Continuity is built on — and then re-broadcasts the phone's
    ///   own clipboard back to it. Checking `types` first costs nothing, because declaring types
    ///   does not transfer data.
    /// - **Concealed content is a password.** Password managers mark their copies concealed
    ///   precisely so tools like this leave them alone. Syncing one would put a password on the
    ///   network. That is skipped on both paths, explicit or not.
    func readClipboard(automatic: Bool = false) -> String? {
        let pasteboard = NSPasteboard.general
        let types = Set(pasteboard.types ?? [])

        // Never, on any path.
        guard !types.contains(PasteboardMarker.concealed) else { return nil }

        if automatic {
            guard !types.contains(PasteboardMarker.remote),
                  !types.contains(PasteboardMarker.transient),
                  !types.contains(PasteboardMarker.autoGenerated)
            else { return nil }
        }

        guard let text = pasteboard.string(forType: .string) else { return nil }
        guard text.utf8.count <= LinkProtocol.maxClipboardBytes else { return nil }
        return text
    }

    func writeClipboard(_ text: String) {
        guard text.utf8.count <= LinkProtocol.maxClipboardBytes else { return }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // MARK: - Status

    func currentStatus(hostName: String) -> HostStatus {
        HostStatus(
            hostName: hostName,
            accessibilityGranted: InputSynthesizer.isTrusted,
            volume: outputVolume(),
            muted: isMuted(),
            batteryLevel: batteryLevel(),
            isCharging: isCharging(),
            frontmostApp: NSWorkspace.shared.frontmostApplication?.localizedName,
            displayWidth: desktopSize.width,
            displayHeight: desktopSize.height
        )
    }

    /// Union of every active display, matching the space `InputSynthesizer` moves the cursor in.
    private var desktopSize: CGSize {
        var count: UInt32 = 0
        guard CGGetActiveDisplayList(0, nil, &count) == .success, count > 0 else { return .zero }
        var displays = [CGDirectDisplayID](repeating: 0, count: Int(count))
        guard CGGetActiveDisplayList(count, &displays, &count) == .success else { return .zero }

        var bounds = CGRect.null
        for display in displays.prefix(Int(count)) {
            bounds = bounds.union(CGDisplayBounds(display))
        }
        return bounds.isNull ? .zero : bounds.size
    }

    // MARK: Volume (CoreAudio)

    private var defaultOutputDevice: AudioDeviceID? {
        var address = AudioObjectPropertyAddress(
            mSelector: kAudioHardwarePropertyDefaultOutputDevice,
            mScope: kAudioObjectPropertyScopeGlobal,
            mElement: kAudioObjectPropertyElementMain
        )
        var deviceID = AudioDeviceID(0)
        var size = UInt32(MemoryLayout<AudioDeviceID>.size)
        let status = AudioObjectGetPropertyData(
            AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &deviceID
        )
        return status == noErr && deviceID != kAudioObjectUnknown ? deviceID : nil
    }

    private func volumeAddress() -> AudioObjectPropertyAddress {
        AudioObjectPropertyAddress(
            mSelector: kAudioHardwareServiceDeviceProperty_VirtualMainVolume,
            mScope: kAudioDevicePropertyScopeOutput,
            mElement: kAudioObjectPropertyElementMain
        )
    }

    func outputVolume() -> Double? {
        guard let device = defaultOutputDevice else { return nil }
        var address = volumeAddress()
        guard AudioObjectHasProperty(device, &address) else { return nil }

        var volume = Float32(0)
        var size = UInt32(MemoryLayout<Float32>.size)
        let status = AudioObjectGetPropertyData(device, &address, 0, nil, &size, &volume)
        return status == noErr ? Double(volume) : nil
    }

    func setOutputVolume(_ value: Double) {
        guard let device = defaultOutputDevice else { return }
        var address = volumeAddress()
        guard AudioObjectHasProperty(device, &address) else { return }

        var settable = DarwinBoolean(false)
        guard AudioObjectIsPropertySettable(device, &address, &settable) == noErr, settable.boolValue else { return }

        var volume = Float32(min(max(value, 0), 1))
        AudioObjectSetPropertyData(
            device, &address, 0, nil, UInt32(MemoryLayout<Float32>.size), &volume
        )
    }

    func isMuted() -> Bool {
        guard let device = defaultOutputDevice else { return false }
        var address = AudioObjectPropertyAddress(
            mSelector: kAudioDevicePropertyMute,
            mScope: kAudioDevicePropertyScopeOutput,
            mElement: kAudioObjectPropertyElementMain
        )
        guard AudioObjectHasProperty(device, &address) else { return false }

        var muted = UInt32(0)
        var size = UInt32(MemoryLayout<UInt32>.size)
        let status = AudioObjectGetPropertyData(device, &address, 0, nil, &size, &muted)
        return status == noErr && muted == 1
    }

    // MARK: Battery (IOKit)

    private func powerSourceDescription() -> [String: Any]? {
        guard let blob = IOPSCopyPowerSourcesInfo()?.takeRetainedValue(),
              let sources = IOPSCopyPowerSourcesList(blob)?.takeRetainedValue() as? [CFTypeRef]
        else { return nil }

        for source in sources {
            guard let description = IOPSGetPowerSourceDescription(blob, source)?.takeUnretainedValue() as? [String: Any],
                  description[kIOPSTypeKey] as? String == kIOPSInternalBatteryType
            else { continue }
            return description
        }
        return nil
    }

    func batteryLevel() -> Double? {
        guard let description = powerSourceDescription(),
              let current = description[kIOPSCurrentCapacityKey] as? Int,
              let max = description[kIOPSMaxCapacityKey] as? Int,
              max > 0
        else { return nil }
        return Double(current) / Double(max)
    }

    func isCharging() -> Bool {
        guard let description = powerSourceDescription() else { return false }
        if let charging = description[kIOPSIsChargingKey] as? Bool { return charging }
        return description[kIOPSPowerSourceStateKey] as? String == kIOPSACPowerValue
    }
}
